# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
    config.vm.define "rocky-01" do | w |
      w.vm.box = "generic/rocky8"
      w.vm.hostname = "rocky-01"
      w.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
        vb.name = "rocky-01"
      end
      w.vm.synced_folder ".", "/vagrant", type: "rsync"
      w.vm.provision :shell, inline: <<-EOEO
        
        echo "Install dependencies"
        sudo dnf install -y dnf-plugins-core jq bridge-utils

        echo "Install containerd.io from docker repository"
        sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        sudo dnf install -y containerd.io

        containerd config default | sudo tee /etc/containerd/config.toml

        sudo systemctl restart containerd

        echo "Install cni-plugin"
        wget https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz
        sudo mkdir -p /opt/cni/bin
        sudo tar Cxzvvf /opt/cni/bin cni-plugins-linux-amd64-v1.0.1.tgz

        echo "Configure ctr autocompletion"
        wget https://raw.githubusercontent.com/containerd/containerd/main/contrib/autocomplete/ctr
        mkdir -p /home/vagrant/.bash_autocompletion
        mv ctr /home/vagrant/.bash_autocompletion/ctr
        echo "source /home/vagrant/.bash_autocompletion/ctr" >> /home/vagrant/.bashrc

        echo "Install nerdctl"
        wget https://github.com/containerd/nerdctl/releases/download/v0.17.0/nerdctl-0.17.0-linux-amd64.tar.gz
        sudo tar Cxzvvf /usr/bin nerdctl-0.17.0-linux-amd64.tar.gz
        echo "source <(nerdctl completion bash)" >> /home/vagrant/.bashrc

        echo "Reload bashrc"
        source /home/vagrant/.bashrc

        echo "holiwi"

      EOEO
    end
  
  
  end
  