# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # master
  config.vm.define "master" do | master |
    master.vm.box = "generic/rocky8"
    master.vm.hostname = "master.localcluster"
    master.vm.network "private_network", ip: "10.0.200.101", virtualbox__intnet: "NatNetwork"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "master.localcluster"
    end
    master.vm.synced_folder ".", "/vagrant", type: "rsync"
    master.vm.provision :shell, path: "scripts/bootstrap.sh"
    master.vm.provision :shell, path: "scripts/setup-master.sh"
  end
  
  # node01
  config.vm.define "node01" do | node01 |
    node01.vm.box = "generic/rocky8"
    node01.vm.hostname = "node01.localcluster"
    node01.vm.network "private_network", ip: "10.0.200.102", virtualbox__intnet: "NatNetwork"
    node01.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
      vb.name = "node01.localcluster"
    end
    node01.vm.synced_folder ".", "/vagrant", type: "rsync"
    node01.vm.provision :shell, path: "scripts/bootstrap.sh"
    node01.vm.provision :shell, path: "scripts/setup-node.sh"
  end


end
